django/function-based-users-views/the_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='the_users_app:home')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),
]

django/function-based-users-views/users/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views


app_name = 'the_users_app'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name='edit'),
]

django/function-based-users-views/users/models.py
from django.db import models

# Create your models here.

django/function-based-users-views/users/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as log_in_the_user
from django.contrib.auth import logout as log_out_the_user
from django.contrib.auth.models import User

from django.db import IntegrityError


def sign_up(request):
    if request.method == 'POST':
        username_in_view = request.POST.get('username_in_form')
        password_in_view = request.POST.get('password_in_form')
        password_confirm_in_view = request.POST.get('password_confirm_in_form')
        if password_in_view != password_confirm_in_view:
            message = 'Passwords do not match'
            context = {
                'message': message
            }
            return render(request, 'registration/signup.html', context)
        try:
            the_new_user = User.objects.create_user(
                username=username_in_view,
                password=password_in_view
            )
            # logout(request)
            return HttpResponseRedirect(reverse('the_users_app:login'))

        except IntegrityError as e:
            print('type(e): ', type(e))
            e.message = 'User already exists: ' + username_in_view
            context = {
                'message': e.message
            }
            return render(request, 'registration/signup.html', context)

        except ValueError as e:
            print('type(e): ', type(e))
            e.message = 'Please provide a username'
            context = {
                'message': e.message
            }
            return render(request, 'registration/signup.html', context)

    return render(request, 'registration/signup.html')


def login(request):
    """
    Function-based view to display the Login form on `GET` request,
    and attempt to log in the user on `POST` request.
    """
    if request.method == 'POST':
        username_in_view = request.POST.get('username_in_form')
        password_in_view = request.POST.get('password_in_form')
        user = authenticate(username=username_in_view, password=password_in_view)
        if user is not None:
            log_in_the_user(request, user)
        return HttpResponseRedirect(reverse('the_users_app:home'))

    return render(request, 'registration/login.html')


def logout(request):
    """
    Function-based view to log out the user on `POST` request.
    """
    log_out_the_user(request)
    return HttpResponseRedirect(reverse('the_users_app:home'))


def edit(request):
    """
    Function-based view to display edit `User` form on `GET` request,
    and change `User` on `POST` request.
    """
    print('request.user: ', request.user)
    if request.method == 'POST':
        username_in_view = request.POST.get('username_in_form')
        if username_in_view != '' and request.user.username != username_in_view:
            print("WOMP WOMP!!! Tricksie Hobbitses!!")
            context = {
                'message': "Editing user information that are not you is forbidden!"
            }
            return render(request, 'registration/edit.html', context)

        current_user = get_object_or_404(User, username=username_in_view)
        print("We got a legit USER!!!")
        print('current_user: ', current_user)
        
        password_in_view = request.POST.get('password_in_form')
        password_confirm_in_view = request.POST.get('password_confirm_in_form')
        print('POST!!!')
        return HttpResponseRedirect(reverse('the_users_app:home'))

    return render(request, 'registration/edit.html')
    

django/function-based-users-views/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Function-Based Users Views{% endblock %}</title>
</head>
<body>
    <a href="/admin/auth/user/" target="_blank">Django Admin Interface - Users</a>
    <br>
    <a href="/admin/" target="_blank">Django Admin Interface</a>
    <br>
    <a href={% url 'the_users_app:home' %}>Go to Home</a>
    <br>
    <a href={% url 'the_users_app:login' %}>Login Page, PLEASE!</a>
    <br>
    <a href={% url 'the_users_app:signup' %}>Signup Page, PLEASE!</a>
    <br>
    <a href={% url 'the_users_app:logout' %}>Let me OUT, PLEASE!</a>
    <br>
    <a href={% url 'the_users_app:edit' %}>Edit me, PLEASE!</a>
    <br>
    {% block content %}
    {% endblock content %}
</body>
</html>

django/function-based-users-views/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>

{% if user.is_authenticated %}
<p>Welcome, {{ user | capfirst }}</p>
<a href={% url 'the_users_app:logout' %}>Log me OUT, PLEASE!</a>
<br>
{% else %}
<p>You're a Nobody: {{ user }}!</p>
<a href={% url 'the_users_app:login' %}>Login Page, PLEASE!</a>
<br>
<a href={% url 'the_users_app:signup' %}>Sigunup Page, PLEASE!</a>
<br>
{% endif %}

{% endblock content %}